networks:
  sadeem:
    external: true

services:
  stain-stingray:
    networks:
      - sadeem
    container_name: "${CONTAINER_NAME}"
    image: "sadeemtech/${CONTAINER_NAME}:${CONTAINER_TAG}"
    restart: always
    ports:
      - 8000:8000
    build:
      context: ../../../
      dockerfile: ./docker/builds/local/Dockerfile
      args:
        CONNECTION_STRING: "${CONNECTION_STRING}"
