version: "3.9"

networks:
    sadeem:
        external: true

services:
    violet-owl:
        networks:
            - sadeem
        container_name: "${CONTAINER_NAME}"
        image: "sadeem/${CONTAINER_NAME}:${CONTAINER_TAG}"
        restart: always
        ports:
          - 8000:8000
        build:
            context: .
            dockerfile: Dockerfile.local
            args:
              CONNECTION_STRING: "${CONNECTION_STRING}"

