version: "3.9"

services:
    violet-owl:
        container_name: "${CONTAINER_NAME}"
        image: "sadeem/${CONTAINER_NAME}:${CONTAINER_TAG}"
        restart: always
        expose:
          - "${PORT}"
        build:
            context: .
            dockerfile: Dockerfile
            args:
              CONNECTION_STRING: "${CONNECTION_STRING}"
