version: '3.9'

networks:
    money-transfer:
        external: true

services:
    api:
        container_name: api
        image: sadeem/money-transfer:v1.0
        restart: always
        networks:
            - money-transfer
        expose:
            - "${PORT}"
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .env:/.env
            - ./public:/public
            - ./private:/private
            - ./docs:/docs
            - ./json_google:/json_google

    postgres:
        container_name: postgres
        image: postgis/postgis:16-3.4-alpine
        restart: always
        networks:
            - money-transfer
        expose:
            - "${PG_PORT}"
        environment:
            POSTGRES_USER: "${PG_USER}"
            POSTGRES_DB: "${PG_NAME}"
            POSTGRES_PASSWORD: "${PG_PASS}"
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - ./docker/postgres/data:/var/lib/postgresql/data
            - ./docker/postgres/root:/root
              
    nginx:
        container_name: nginx
        image: nginx:stable-alpine
        restart: always
        networks:
            - money-transfer
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./docker/nginx/logs:/var/log/nginx
            - ./docker/nginx/conf/:/etc/nginx/conf.d/:ro
            - ./docker/nginx/certbot/www:/var/www/certbot/:ro
            - ./docker/nginx/certbot/conf/:/etc/nginx/ssl/:ro
    
    certbot:
        container_name: certbot
        image: certbot/certbot:v2.8.0
        restart: no
        networks:
            - money-transfer
        volumes:
            - ./docker/nginx/certbot/www:/var/www/certbot/:rw
            - ./docker/nginx/certbot/conf/:/etc/letsencrypt/:rw
