services:
  athan:
    container_name: "${CONTAINER_NAME}"
    image: "ogjughead/${CONTAINER_NAME}:${CONTAINER_TAG}"
    restart: always
    expose:
      - "${PORT}"
    build:
      context: ../../../
      dockerfile: ./docker/builds/lab/Dockerfile
      args:
        CONNECTION_STRING: "${CONNECTION_STRING}"
