version: "3.9"

services:
  shared-postgres:
    image: postgis/postgis:16-3.4
    container_name: shared-postgres
    restart: always
    environment:
      POSTGRES_USER: athan
      POSTGRES_PASSWORD: 3bc7f707-1a4d-48c1-a5bd-0d243b655aa7
      POSTGRES_DB: athan
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - shared-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U athan"]
      interval: 5s
      timeout: 5s
      retries: 10

  athan:
    container_name: "${CONTAINER_NAME}"
    build:
      context: ../../../
      dockerfile: ./docker/builds/lab/Dockerfile
    image: "ogjughead/${CONTAINER_NAME}:${CONTAINER_TAG}"
    restart: always
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    depends_on:
      shared-postgres:
        condition: service_healthy
    networks:
      - shared-net

networks:
  shared-net:
    external: true
